
import Navbar from "./constants/Navbar/Navbar";
import Image from "next/image";
import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import {
  B1, B2, B3, B, E1, E2, logo, Rect, star2, star5, star6, star8, star9, star12, star14, star15, star16, star17, star18, star19, vect1, vect2, vect3, vect4, vect5
} from "../public";

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'auto',
  variable: "--poppins"
});

const grocerries = [
B1, B2, B3, B, E1, E2, Rect, star2, star5, star6, star8, star9, star12, star14, star15, star16, star17, star18, star19, vect1, vect2, vect3, vect4, vect5
]

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {grocerries.map((groc, i) => <Image key={i} src={groc} alt={groc} className={`groc-${i} fixed`} />)}
        {children}
      </body>
    </html>
  )
}
